import { Box } from "@mui/material"
import '../styles/globals.css'
import UserAvatar from "@/components/atoms/UserAvatar"
import TextInfo from "@/components/atoms/TextInfo"
import Header from "@/components/molecules/Header"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>     
      <Header />
        {children}
        </body>
    </html>
  )
}
